### PR TITLE
[MPH-189] Get rid of commons lang3 dependency

### PR DESCRIPTION
**Pull request by Giovds**
Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [MPH-189](https://issues.apache.org/jira/browse/MPH-189) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MPH-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MPH-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [ ] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [ ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by Giovds** [comment]
This requires the DefaultArtifactVersion to drop commons-lang3 in the maven-artifact module. This was just recently done with https://issues.apache.org/jira/browse/MNG-8146 and PR #1564 in core.

After that version bump is required here

**Review by slawekjaranowski — APPROVED** [review]
Change looks ok ...

But we should figure out how to avoid calling private methods at all - of course it is another issue and PR

**Comment by Giovds** [comment]
I agree. 

The main reason I kept it, is because it's used only for test code which was already based on reflection. I didn't want to changing the access modifiers of the actual class. Like you said, I wanted to focus this PR on removing the dependency.

**Comment by michael-o** [comment]
Will try to check in a couple of days.

**Review by michael-o — CHANGES_REQUESTED** [review]
You so often repeat the same lines that it would make sense to move that to a private method.

**Review by michael-o — APPROVED** [review]
Good to squash and merge.

**Review by slachiewicz — APPROVED** [review]

**Comment by jira-importer** [comment]
Resolve #167

**Comment by jira-importer** [comment]
Resolve #167

**Pull request merged**
