### PR TITLE
[MPH-171] Preserve plugin repositories from project pom

### PR DESCRIPTION
**Pull request by t-8ch**
Fixes MPH-171

- [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

### CODE REVIEW

**Review by slachiewicz — APPROVED** [review]

**Comment by slachiewicz** [comment]
Thank you for patch.

**Comment by t-8ch** [comment]
@slachiewicz Is there any offical released planned containing this PR?
Currently this is blocking me and I'd like to know if it's worth working around the issue.

**Comment by slachiewicz** [comment]
Yes it's on my very short list to do release

**Comment by michael-o** [comment]
> @slachiewicz Is there any offical released planned containing this PR?
> Currently this is blocking me and I'd like to know if it's worth working around the issue.

We are volunteers, we don't have any hard schedules.

**Comment by t-8ch** [comment]
@slachiewicz Thanks a lot!

@michael-o Of course; this was not meant to apply pressure or extract any sort of commitment.

**Comment by jira-importer** [comment]
Resolve #305

**Comment by jira-importer** [comment]
Resolve #305

**Pull request closed without merging**
